
// Para el RFID se usa el SPI4
#define PIN_RFID_MOSI PE_6
#define PIN_RFID_MISO PE_5
#define PIN_RFID_SCK PE_2
#define PIN_RFID_CS PE_4
#define PIN_RFID_RESET PE_3

//LEDS
#define PIN_LED_DOOR_BLOCKED D0
#define PIN_LED_DOOR_OPEN D1

//BUTTONS
#define PIN_BUTTON_DOOR_BLOCK D7
#define PIN_BUTTON_DOORBELL D6

//MAGNETIC SENSORS
#define PIN_MAGNET_SENSOR_1 D8


//KEYPAD
#define KEYPAD_NUMBER_OF_ROWS       4
#define KEYPAD_NUMBER_OF_COLS       4
#define TIMEOUT_CODE                10000
#define TIMEOUT_DOOR_OPEN           10000 
#define LED_BLINK_INTERVAL          1000       

//Motor
#define PIN_MOTOR_LOCK   PB_11
#define MOTOR_POS_LOCKED 15
#define MOTOR_POS_OPEN 55
#define MOTOR_CLOSE_DELAY 1000 //ms
//Speaker
#define PIN_SPEAKER PB_4

#define WRONG_ID_BLINKS 6
#define TIME_RESTART_ALARM 10000000 //us

//MQTT
#define PIN_MQTT_TX PC_12
#define PIN_MQTT_RX PD_2
#define MQTT_BAUDRATE 115200

#define PIN_MQTT_LED D2
#define PIN_MQTT_LED_BLINK_TIME 100 //ms

#define KEEP_ALIVE_INTERVAL 9000 //ms
